name: Deploy Snapshots

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'
        server-id: central
        server-username: SONATYPE_USERNAME
        server-password: SONATYPE_PASSWORD

    - name: Deploy snapshot
      run: mvn -B deploy --file pom.xml
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

    - name: Deploy to KGH Test
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-DEPLOYKGHTEST'
        method: 'POST'
        bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
        customHeaders: '{"Accept": "application/json"}'

    - name: Deploy to Gladi
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://bamboo-ci.pih-emr.org/rest/api/latest/queue/OMRS-DEPLOYGLADI'
        method: 'POST'
        bearerToken: ${{ secrets.PIH_BAMBOO_API_KEY }}
        customHeaders: '{"Accept": "application/json"}'